apiVersion: v1
kind: ConfigMap
metadata:
  name: airbnb-config
  namespace: airbnb
data:
  MONGODB_URI: "mongodb://root:pass123@mongodb:27017/airbnb?authSource=admin"
  KAFKA_BROKERS: "kafka:9092"
  JWT_EXPIRES_IN: "7d"
  CLIENT_ORIGIN: "http://localhost"
  NODE_ENV: "production"
  LLM_PROVIDER: "ollama"
  LLM_MODEL: "llama3"
  CORS_ORIGIN: "http://localhost"
