apiVersion: v1
kind: Secret
metadata:
  name: airbnb-secrets
  namespace: airbnb
type: Opaque
data:
  # Base64 encoded values
  # JWT_SECRET: "your_jwt_secret" -> eW91cl9qd3Rfc2VjcmV0
  JWT_SECRET: "eW91cl9qd3Rfc2VjcmV0"
  # MONGODB_ROOT_PASSWORD: "pass123" -> cGFzczEyMw==
  MONGODB_ROOT_PASSWORD: "cGFzczEyMw=="
  # Add other secrets here (API keys, etc.)
  # TAVILY_API_KEY: ...
  # GOOGLE_API_KEY: ...
